### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by benwoodward** [oskarhane/actus#3]
Fantastic work on Actus. I'm considering building upon it and potentially using it in a commercial project, however, I noticed that there is no license attached to the repository. Would appreciate it if you could add one, thanks!

**Comment by oskarhane** [comment]
Thanks! 
I've added a LICENSE file now - but the packages already had licenses in their `package.json`.

**Comment by benwoodward** [comment]
Oh I missed that. Ok, thanks!
