### ISSUE TITLE
A11y: on:mouseover must be accompanied by on:focus

### ISSUE THREAD

**Issue by ceifa** [oskarhane/actus#6]
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/mouse-events-have-key-events.md

https://github.com/oskarhane/actus/blob/cb8f2135b04380613afe734e0b26a65f17cadcbc/packages/svelte/src/Component.svelte#L211

**Comment by oskarhane** [comment]
Thanks, happy to take a PR if you have the ability to.
