### ISSUE TITLE
Feature request: Add possibility to override default behavior of the browsers

### ISSUE THREAD

**Issue by ceifa** [oskarhane/actus#8]
If I enable the `ctrlKey` and set the `toggleKey` to `K`(just like github does), it will not work because of the default browser behavior for the Ctrl+K command.

This happens because the event attached to look for the keys is `onkeyup` and these browser behaviors happens on `onkeydown`. If we just change the `onkeyup` to `onkeydown` it will work great because of the `preventDefault`.

Is there a good reason to use the `onkeyup` instead of `onkeydown`?

**Comment by ceifa** [comment]
Related to #5

**Comment by oskarhane** [comment]
Good catch! No good reason to keep it, feel free to open a PR if you're able to.
